---
dependency:
  name: galaxy
  options:
    role-file: roles/requirements.yml
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
verifier:
  name: ansible
provisioner:
  name: ansible
  playbooks:
    converge: ../../playbooks/init_dev_environment.yml
  options:
      vvv: false

